apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec:
  selector:
    app: flaskapp
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels: 
    app: flaskapp
spec:
  selector: 
    matchLabels:
     app: flaskapp
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: dharunrk/flaskapp:test
          ports:
            - containerPort: 5000
          env:
            - name: DISABLE_WEB_APP
              value: "flase"
            


